#!/usr/bin/env bash

set -euo pipefail

BIN_DIR="${HOME}/.local/bin"
TASKS_FILE="${HOME}/.config/taskarena/tasks.json"
CURRENT_TASK_FILE="${HOME}/.config/taskarena/current.json"
COMPLETED_TASKS_FILE="${HOME}/.config/taskarena/completed.json"

mkdir -p "$BIN_DIR"

for file in taskarena task-pull task-push; do
    if [[ ! -f "$file" ]]; then
        echo "Error: '$file' not found." >&2
        exit 1
    fi

    cp --update "$file" "$BIN_DIR/$file"
done

if [[ "${1:-}" == "--clean" || "${1:-}" == "clean" ]]; then
    rm -f "$TASKS_FILE"
    echo "Removed $TASKS_FILE"
    rm -f "$CURRENT_TASK_FILE"
    echo "Removed $CURRENT_TASK_FILE"
    rm -f "$COMPLETED_TASKS_FILE"
    echo "Removed $COMPLETED_TASKS_FILE"
fi
