#!/bin/bash

set -euo pipefail

tag=$(walker --dmenu -p "Tag (optional):") || true

taskarena pull --tag $tag
output=$(taskarena status --format notify)
task_line=$(echo "$output" | tail -n 1)

notify-send -a "Tasks" "Next task" "$task_line"
